version: '3'

services:
  apache:
    restart: always
    build:
      context: ./apache
      args:                                                                      
        THEME: brc_automad_theme
    ports:
      - "${PORT}:80"
    volumes:
      - ${CONFIG}:/var/www/html/config/:Z
      - ${PAGES}:/var/www/html/pages/:Z
      - ${SHARED}:/var/www/html/shared/:Z
